### ISSUE TITLE
New servers added with 7.0.0 update

### ISSUE THREAD

**Issue by Egrirt** [buggerman/SwitchBlockerForPiHole#3]
The following telemetry servers (and probably a few more) were activated with the latest 7.0.0 update
app-b01.lp1.npns.srv.nintendo.net
dragons.hac.lp1.dragons.nintendo.net
scsi-policy-lp1.cdn.nintendo.net
scsi-download.lp1.scsi.srv.nintendo.net

**Comment by buggerman** [comment]
Added. Thanks!
